name: ct312h_project
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  intl: ^0.20.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  pocketbase: ^0.22.0
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.2
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/lanara.png
    - .env
    - assets/
    - assets/images/
  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
  - family: Anton
    fonts:
      - asset: assets/fonts/Anton-Regular.ttf
  - family: Reika
    fonts:
      - asset: assets/fonts/Reika-Regular.otf
  - family: Genty
    fonts:
      - asset: assets/fonts/GentyDemo-Regular.ttf

